export const TEAM_META = {
  ALG: { nameZh: "阿尔及利亚", flag: "🇩🇿" },
  ARG: { nameZh: "阿根廷", flag: "🇦🇷" },
  AUS: { nameZh: "澳大利亚", flag: "🇦🇺" },
  AUT: { nameZh: "奥地利", flag: "🇦🇹" },
  BEL: { nameZh: "比利时", flag: "🇧🇪" },
  BIH: { nameZh: "波黑", flag: "🇧🇦" },
  BRA: { nameZh: "巴西", flag: "🇧🇷" },
  CAN: { nameZh: "加拿大", flag: "🇨🇦" },
  CIV: { nameZh: "科特迪瓦", flag: "🇨🇮" },
  COD: { nameZh: "刚果民主共和国", flag: "🇨🇩" },
  COL: { nameZh: "哥伦比亚", flag: "🇨🇴" },
  CRO: { nameZh: "克罗地亚", flag: "🇭🇷" },
  CPV: { nameZh: "佛得角", flag: "🇨🇻" },
  CUW: { nameZh: "库拉索", flag: "🇨🇼" },
  CZE: { nameZh: "捷克", flag: "🇨🇿" },
  ECU: { nameZh: "厄瓜多尔", flag: "🇪🇨" },
  EGY: { nameZh: "埃及", flag: "🇪🇬" },
  ENG: { nameZh: "英格兰", flag: "🏴" },
  ESP: { nameZh: "西班牙", flag: "🇪🇸" },
  FRA: { nameZh: "法国", flag: "🇫🇷" },
  GER: { nameZh: "德国", flag: "🇩🇪" },
  GHA: { nameZh: "加纳", flag: "🇬🇭" },
  HAI: { nameZh: "海地", flag: "🇭🇹" },
  IRQ: { nameZh: "伊拉克", flag: "🇮🇶" },
  IRN: { nameZh: "伊朗", flag: "🇮🇷" },
  JOR: { nameZh: "约旦", flag: "🇯🇴" },
  JPN: { nameZh: "日本", flag: "🇯🇵" },
  KOR: { nameZh: "韩国", flag: "🇰🇷" },
  KSA: { nameZh: "沙特阿拉伯", flag: "🇸🇦" },
  MAR: { nameZh: "摩洛哥", flag: "🇲🇦" },
  MEX: { nameZh: "墨西哥", flag: "🇲🇽" },
  NED: { nameZh: "荷兰", flag: "🇳🇱" },
  NOR: { nameZh: "挪威", flag: "🇳🇴" },
  NZL: { nameZh: "新西兰", flag: "🇳🇿" },
  PAN: { nameZh: "巴拿马", flag: "🇵🇦" },
  PAR: { nameZh: "巴拉圭", flag: "🇵🇾" },
  POR: { nameZh: "葡萄牙", flag: "🇵🇹" },
  QAT: { nameZh: "卡塔尔", flag: "🇶🇦" },
  RSA: { nameZh: "南非", flag: "🇿🇦" },
  SCO: { nameZh: "苏格兰", flag: "🏴" },
  SEN: { nameZh: "塞内加尔", flag: "🇸🇳" },
  SUI: { nameZh: "瑞士", flag: "🇨🇭" },
  SWE: { nameZh: "瑞典", flag: "🇸🇪" },
  TUN: { nameZh: "突尼斯", flag: "🇹🇳" },
  TUR: { nameZh: "土耳其", flag: "🇹🇷" },
  URU: { nameZh: "乌拉圭", flag: "🇺🇾" },
  USA: { nameZh: "美国", flag: "🇺🇸" },
  UZB: { nameZh: "乌兹别克斯坦", flag: "🇺🇿" }
};

export function getTeamMeta(code) {
  return TEAM_META[code] ?? null;
}
